//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.12.04 at 11:13:19 AM GMT 
//

package ie.gmit.sw.ds.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for accounts complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="accounts"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="acc_no" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accounts", namespace = "http://ds.sw.gmit.ie/models/", propOrder = { "accNo", "fname", "surname",
		"dob", "address" })
public class Accounts {

	@XmlElement(name = "acc_no", namespace = "http://ds.sw.gmit.ie/models/", required = true)
	protected String accNo;

	@XmlElement(namespace = "http://ds.sw.gmit.ie/models/", required = true)
	protected String fname;

	@XmlElement(namespace = "http://ds.sw.gmit.ie/models/", required = true)
	protected String surname;

	@XmlElement(namespace = "http://ds.sw.gmit.ie/models/", required = true)
	protected String dob;

	@XmlElement(namespace = "http://ds.sw.gmit.ie/models/", required = true)
	protected String address;

	/**
	 * Gets the value of the accNo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAccNo() {
		return accNo;
	}

	/**
	 * Sets the value of the accNo property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAccNo(String value) {
		this.accNo = value;
	}

	/**
	 * Gets the value of the fname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFname() {
		return fname;
	}

	/**
	 * Sets the value of the fname property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setFname(String value) {
		this.fname = value;
	}

	/**
	 * Gets the value of the surname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSurname() {
		return surname;
	}

	/**
	 * Sets the value of the surname property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setSurname(String value) {
		this.surname = value;
	}

	/**
	 * Gets the value of the dob property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDob() {
		return dob;
	}

	/**
	 * Sets the value of the dob property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDob(String value) {
		this.dob = value;
	}

	/**
	 * Gets the value of the address property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * Sets the value of the address property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAddress(String value) {
		this.address = value;
	}

}
