//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.12.04 at 11:13:19 AM GMT 
//


package com.webclient.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="rentalDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="returnDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="accounts" type="{http://ds.sw.gmit.ie/models/}accounts"/&gt;
 *         &lt;element name="cars" type="{http://ds.sw.gmit.ie/models/}cars" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "rentalDate",
    "returnDate",
    "accounts",
    "cars"
})
@XmlRootElement(name = "rentals", namespace = "http://ds.sw.gmit.ie/models/")
public class Rentals {

    @XmlElement(namespace = "http://ds.sw.gmit.ie/models/")
    protected int id;
    @XmlElement(namespace = "http://ds.sw.gmit.ie/models/", required = true)
    protected String rentalDate;
    @XmlElement(namespace = "http://ds.sw.gmit.ie/models/", required = true)
    protected String returnDate;
    @XmlElement(namespace = "http://ds.sw.gmit.ie/models/", required = true)
    protected Accounts accounts;
    @XmlElement(namespace = "http://ds.sw.gmit.ie/models/", required = true)
    protected List<Cars> cars;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the rentalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRentalDate() {
        return rentalDate;
    }

    /**
     * Sets the value of the rentalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRentalDate(String value) {
        this.rentalDate = value;
    }

    /**
     * Gets the value of the returnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnDate() {
        return returnDate;
    }

    /**
     * Sets the value of the returnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnDate(String value) {
        this.returnDate = value;
    }

    /**
     * Gets the value of the accounts property.
     * 
     * @return
     *     possible object is
     *     {@link Accounts }
     *     
     */
    public Accounts getAccounts() {
        return accounts;
    }

    /**
     * Sets the value of the accounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accounts }
     *     
     */
    public void setAccounts(Accounts value) {
        this.accounts = value;
    }

    /**
     * Gets the value of the cars property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cars property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCars().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cars }
     * 
     * 
     */
    public List<Cars> getCars() {
        if (cars == null) {
            cars = new ArrayList<Cars>();
        }
        return this.cars;
    }

}
