//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.12.04 at 11:13:19 AM GMT 
//


package ie.gmit.sw.ds.models;

import java.io.Serializable;

public class Cars implements Serializable{

	private static final long serialVersionUID = 1L;
	protected String carMake;
    protected String carModel;
    protected String carReg;
    protected String carSize;
    protected String fuelType;
    protected int rentalId;
    protected int seats;
    protected String transmission;

    public String getCarMake() {
        return carMake;
    }

    public void setCarMake(String value) {
        this.carMake = value;
    }

    public String getCarModel() {
        return carModel;
    }

    public void setCarModel(String value) {
        this.carModel = value;
    }

    public String getCarReg() {
        return carReg;
    }

    public void setCarReg(String value) {
        this.carReg = value;
    }

    public String getCarSize() {
        return carSize;
    }

    public void setCarSize(String value) {
        this.carSize = value;
    }

    public String getFuelType() {
        return fuelType;
    }

    public void setFuelType(String value) {
        this.fuelType = value;
    }

    public int getRentalId() {
        return rentalId;
    }

    public void setRentalId(int value) {
        this.rentalId = value;
    }

    public int getSeats() {
        return seats;
    }

    public void setSeats(int value) {
        this.seats = value;
    }

    public String getTransmission() {
        return transmission;
    }

    public void setTransmission(String value) {
        this.transmission = value;
    }

}
