//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.12.04 at 11:13:19 AM GMT 
//

package ie.gmit.sw.ds.models;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class Rentals implements Serializable{

	private static final long serialVersionUID = 1L;
	protected int id;
	protected String rentalDate;
	protected String returnDate;
	protected Accounts accounts;
	protected List<Cars> cars;

	public int getId() {
		return id;
	}

	public void setId(int value) {
		this.id = value;
	}

	public String getRentalDate() {
		return rentalDate;
	}

	public void setRentalDate(String value) {
		this.rentalDate = value;
	}

	public String getReturnDate() {
		return returnDate;
	}

	public void setReturnDate(String value) {
		this.returnDate = value;
	}

	public Accounts getAccounts() {
		return accounts;
	}

	public void setAccounts(Accounts value) {
		this.accounts = value;
	}

	public List<Cars> getCars() {
		if (cars == null) {
			cars = new ArrayList<Cars>();
		}
		return this.cars;
	}
}
